import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Button } from '@mui/material'
import styles from './button.module.scss'
import { css } from '@mui/styled-engine'

const BgRedColor = css({
  backgroundColor: 'red',
})

export default function MuiTest() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        {/* using module scss */}
        <Button variant='contained' className={styles.redButton}>
          button
        </Button>

        {/* using global style */}
        <Button variant='contained'>red button</Button>

        {/* using emotion */}
        <Button variant='contained' css={BgRedColor}>
          red button
        </Button>
      </main>
    </>
  )
}
