import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Button } from '@mui/material'
import styles from './button.module.scss'

export default function MuiTest() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        {/* using module scss */}
        <Button variant='contained' className={styles.redButton}>
          button
        </Button>

        <Button variant='contained'>red button</Button>

        {/* usding emotion */}
      </main>
    </>
  )
}
